version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://mysql_db:3306/market_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: 19931012
      SPRING_R2DBC_POOL_ENABLED: true
      SPRING_PROFILES_ACTIVE: docker # Указываем профиль docker
    depends_on:
      mysql_db:
        condition: service_healthy

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: market_db
      MYSQL_ROOT_PASSWORD: 19931012
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p19931012"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_data: